[package]
name = "md2docx"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
docx-rs = "0.4.17"
markdown-rs = "0.1.0"
pulldown-cmark = "0.13.0"
serde = "1.0.219"
yaml-front-matter = "0.1.0"
